language: go
sudo: required

go:
  - 1.7

services:
  - redis-server

install:
  - make dependencies

script:
  - make stat

after_success:
  # build aci
  - make clean build_travis_aci
  - mv silo.aci silo-latest-linux-amd64.aci
  # grab pub/pri keys
  - curl -d sec=$BINDER_SEC -d key=unixvoid.pub https://cryo.unixvoid.com/getfile --output unixvoid.pub
  - curl -d sec=$BINDER_SEC -d key=unixvoid.sec https://cryo.unixvoid.com/getfile --output unixvoid.sec
  # sign aci
  - cp deps/sign.sh . && chmod +x sign.sh
  - ./sign.sh $GPG_SEC
  # upload aci to binder
  - curl -i --form sec=$BINDER_SEC --form file=@silo-latest-linux-amd64.aci --form path=rkt/silo/ https://cryo.unixvoid.com/upload
  - curl -i --form sec=$BINDER_SEC --form file=@silo-latest-linux-amd64.aci.asc --form path=rkt/silo/ https://cryo.unixvoid.com/upload
